### ISSUE TITLE
Versió PDF

### ISSUE THREAD

**Issue by ZJaume** [Jautenim/diceware-cat#1]
Seria prou útil una versió en PDF amb vàries columnes per per poder imprimir i estalviar fulls. Com la que hi ha al web [http://world.std.com/%7Ereinhold/dicewarewordlist.pdf](url)

**Comment by 1ma** [comment]
M'agrada com penses. Voldria fer-ho en LaTeX per tenir el codi font del document i no haver de commitejar un blob al repositori, però no en tinc ni puta idea.

Si em pots ajudar accepto Pull Requests, si no... tardaré una mica a penjar-ho.

**Comment by ZJaume** [comment]
Jo tinc alguna idea de Latex, ho miraré a veure si ho puc fer i faig una pull request.

**Comment by ZJaume** [comment]
Ho tinc més o menys, el que passa és que hi ha el problema de la signatura, no se que fer amb ella.
També tinc el dupte de si ficar 4 o 5 columnes, adjunte dos exemples, la diferència serien 7 pàgines.
[cat-wordlist4cols.pdf](https://github.com/1ma/diceware-cat/files/667009/cat-wordlist4cols.pdf)
[cat-wordlist5cols.pdf](https://github.com/1ma/diceware-cat/files/667008/cat-wordlist5cols.pdf)

**Comment by 1ma** [comment]
Tranqui, no la incloguis. Tampoc es pot verificar una firma estampada en un PDF, ha d'estar en text pla. Si algú ho vol fer haurà de fer servir igualment les llistes originals.

En quant al layout crec que em quedo amb el de 5 columnes. Queda una miqueta atapeït però prefereixo menys pàgines.

**Comment by ZJaume** [comment]
La qüestió de la firma és que fot lo bó de Latex, que es pot importar el fitxer en el codi sense haver de copiar i pegar, o bé es fica un arxiu txt sense la firma o caldria copiar i pegar dins del codi.

**Comment by 1ma** [comment]
Ah, merda... Tinc una idea, com veuries preparar-ho tot amb un script en bash que retallés la firma de les llistes que ja existeixen, guardés el resultat en un fitxer temporal i el fés servir per generar el PDF, tot en un pas? Del pal això:

```sh
#!/bin/bash

tail -n +4 ./cat-wordlist-ascii.txt | head -n -16 > ascii-latex.txt
tail -n +4 ./cat-wordlist-utf8.txt | head -n -16 > utf8-latex.txt

# compilat dels PDFs

rm ascii-latex.txt utf8-latex.txt
```

**Comment by ZJaume** [comment]
#2

**Comment by 1ma** [comment]
Implementat a https://github.com/1ma/diceware-cat/pull/2
